# Configuration complète pour la gestion intelligente de la batterie Enphase
# avec prédiction de consommation par analyse historique

# ============================================================================
# PARTIE 1: SENSORS SQL POUR L'ANALYSE HISTORIQUE
# ============================================================================

sensor:
  # Sensor SQL: Consommation moyenne des jours similaires
  - platform: sql
    db_url: sqlite:////config/home-assistant_v2.db
    queries:
      - name: "Consommation Prédite Demain"
        query: >
          WITH tomorrow_weekday AS (
            SELECT CAST(strftime('%w', datetime('now', '+1 day')) AS INTEGER) as weekday
          ),
          similar_days AS (
            SELECT
              s.state,
              s.created_ts,
              strftime('%w', datetime(s.created_ts, 'unixepoch', 'localtime')) as day_of_week
            FROM statistics s
            INNER JOIN statistics_meta sm ON s.metadata_id = sm.id
            WHERE sm.statistic_id = 'sensor.daily_energy_consumption'
              AND s.created_ts > strftime('%s', 'now', '-60 days')
              AND s.created_ts < strftime('%s', 'now', '-1 day')
              AND CAST(strftime('%w', datetime(s.created_ts, 'unixepoch', 'localtime')) AS INTEGER) = (SELECT weekday FROM tomorrow_weekday)
              AND s.state IS NOT NULL
              AND s.state != 'unknown'
              AND s.state != 'unavailable'
          )
          SELECT
            CASE
              WHEN COUNT(*) > 0 THEN ROUND(AVG(CAST(state AS FLOAT)), 2)
              ELSE 5.0
            END as avg_consumption
          FROM similar_days;
        column: "avg_consumption"
        unit_of_measurement: "kWh"

# ============================================================================
# PARTIE 2: TEMPLATE SENSORS (HELPERS)
# ============================================================================

template:
  - sensor:
      # Sensor qui combine consommation prédite et production solaire
      - name: "Déficit Énergétique Prédit Demain"
        unique_id: predicted_energy_deficit_tomorrow
        state: >
          {% set consumption = states('sensor.consommation_predite_demain') | float(5) %}
          {% set production = states('sensor.solcast_pv_forecast_forecast_tomorrow') | float(0) %}
          {{ [consumption - production, 0] | max | round(2) }}
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: measurement
        icon: mdi:battery-alert

      # Sensor qui calcule le SOC nécessaire pour couvrir le déficit
      - name: "SOC Requis Pour Déficit"
        unique_id: soc_required_for_deficit
        state: >
          {% set deficit = states('sensor.deficit_energetique_predit_demain') | float(0) %}
          {% set battery_capacity = 5.0 %}
          {% set soc_needed = (deficit / battery_capacity) * 100 %}
          {{ [soc_needed, 100] | min | round(0) }}
        unit_of_measurement: "%"
        icon: mdi:battery-charging-high

# ============================================================================
# PARTIE 3: RECORDER - CONFIGURATION POUR L'HISTORIQUE
# ============================================================================

recorder:
  # Conservation des états détaillés pendant 10 jours
  purge_keep_days: 10

  # Commit toutes les secondes pour de meilleures performances
  commit_interval: 1

  # Base de données SQLite (par défaut)
  db_url: sqlite:////config/home-assistant_v2.db

  # Inclure les entités importantes pour l'analyse
  include:
    entities:
      # BATTERIE
      - sensor.enphase_battery_soc
      - switch.enphase_battery_charge_from_grid

      # ÉNERGIE
      - sensor.daily_energy_consumption
      - sensor.hourly_energy_consumption
      - sensor.energy_production_today
      - sensor.energy_production_tomorrow_forecast

      # TEMPO
      - sensor.rte_tempo_today
      - sensor.rte_tempo_tomorrow

      # MÉTÉO & SOLEIL
      - weather.home
      - sun.sun

      # SENSORS PRÉDITS (SQL)
      - sensor.consommation_predite_demain
      - sensor.deficit_energetique_predit_demain
      - sensor.soc_requis_pour_deficit

# ============================================================================
# PARTIE 4: BLUEPRINT - PARAMÈTRES RECOMMANDÉS
# ============================================================================

# Configuration à utiliser lors de la création de l'automation depuis le blueprint
# (Copier ces valeurs dans l'interface Home Assistant)

# EXEMPLE DE CONFIGURATION DU BLUEPRINT:
#
# Gestion Intelligente Charge Batterie Enphase (Tempo + Météo)
#
# --- CAPTEURS DE BASE ---
# Capteur SOC Batterie: sensor.enphase_battery_soc
# Capacité Batterie: 5.0 kWh
# Puissance de Charge: 3.84 kW
# Switch Charge depuis Réseau: switch.enphase_battery_charge_from_grid
#
# --- TEMPO ---
# Capteur Tempo Aujourd'hui: sensor.rte_tempo_today
# Capteur Tempo Demain: sensor.rte_tempo_tomorrow
#
# --- HEURES CREUSES ---
# Début Heures Creuses: 22:30:00
# Fin Heures Creuses: 06:30:00
#
# --- MÉTÉO & SOLEIL ---
# Entité Météo: weather.home
# Capteur Lever du Soleil: sun.sun
#
# --- PRODUCTION SOLAIRE ---
# Capteur Prévision Production Solaire: sensor.solcast_pv_forecast_forecast_tomorrow
# Seuil Production Faible: 5.0 kWh
# Seuil Production Moyenne: 15.0 kWh
#
# --- CONSOMMATION HISTORIQUE (NOUVEAU!) ---
# Capteur Consommation Prédite: sensor.consommation_predite_demain
# Activer Prédiction par Consommation Historique: ON
#
# --- AJUSTEMENTS ---
# Ajustement Gap Lever du Soleil: ON
# Consommation Moyenne par Heure: 1.0 kWh/h
#
# --- SOC CIBLES ---
# SOC Minimum pour Charge: 30%
# SOC Minimum Fin Heures Creuses: 80%
# SOC Cible Tempo Rouge: 100%
#
# --- STRATÉGIE ---
# Stratégie de Charge: Optimisée (au dernier moment)
# Notifications de Debug: ON (pour tester, puis OFF)

# ============================================================================
# PARTIE 5: UTILITY METER (OPTIONNEL)
# ============================================================================

# Pour créer des sensors de consommation quotidienne si vous n'en avez pas

utility_meter:
  daily_energy_consumption:
    source: sensor.energy_consumed  # Remplacer par votre sensor d'énergie consommée
    cycle: daily

  hourly_energy_consumption:
    source: sensor.energy_consumed
    cycle: hourly

# ============================================================================
# PARTIE 6: AUTOMATIONS COMPLÉMENTAIRES (OPTIONNEL)
# ============================================================================

automation:
  # Notification quotidienne avec les prédictions
  - id: battery_daily_prediction_notification
    alias: "Batterie - Notification Prédiction Quotidienne"
    trigger:
      - platform: time
        at: "07:00:00"
    action:
      - service: notify.mobile_app  # Adapter selon votre service de notification
        data:
          title: "📊 Prédiction Énergétique Aujourd'hui"
          message: >
            Consommation prévue: {{ states('sensor.consommation_predite_demain') }} kWh
            Production prévue: {{ states('sensor.solcast_pv_forecast_forecast_today') }} kWh
            Déficit prédit: {{ states('sensor.deficit_energetique_predit_demain') }} kWh
            SOC batterie: {{ states('sensor.enphase_battery_soc') }}%
            SOC recommandé: {{ states('sensor.soc_requis_pour_deficit') }}%

  # Forcer mise à jour du sensor SQL à 03h00
  - id: update_consumption_prediction
    alias: "Batterie - MAJ Prédiction Consommation"
    trigger:
      - platform: time
        at: "03:00:00"
    action:
      - service: homeassistant.update_entity
        target:
          entity_id: sensor.consommation_predite_demain

# ============================================================================
# NOTES D'INSTALLATION
# ============================================================================

# 1. Remplacez tous les noms de sensors par VOS sensors réels:
#    - sensor.daily_energy_consumption → Votre sensor de consommation quotidienne
#    - sensor.enphase_battery_soc → Votre sensor SOC Enphase
#    - sensor.solcast_pv_forecast_forecast_tomorrow → Votre sensor production solaire
#
# 2. Ajoutez cette configuration à votre configuration.yaml ou créez des fichiers
#    séparés inclus via:
#    sensor: !include sensors.yaml
#    template: !include templates.yaml
#    automation: !include automations.yaml
#
# 3. Redémarrez Home Assistant après modification
#
# 4. Vérifiez dans Outils de développement > États que les sensors sont créés
#
# 5. Créez l'automation depuis le blueprint avec les paramètres ci-dessus
#
# 6. Activez les notifications de debug pour les premiers jours
#
# 7. Ajustez les seuils selon votre profil de consommation après 1-2 semaines

# ============================================================================
# DÉPANNAGE
# ============================================================================

# Si le sensor SQL ne fonctionne pas:
# 1. Vérifiez les logs: Paramètres > Système > Journaux
# 2. Testez la requête SQL directement dans la base:
#    sqlite3 /config/home-assistant_v2.db "SELECT * FROM statistics_meta WHERE statistic_id LIKE '%consumption%';"
# 3. Vérifiez que vous avez au moins 60 jours d'historique
# 4. Forcez une mise à jour: Services > homeassistant.update_entity

# ============================================================================
# RESSOURCES
# ============================================================================

# Documentation complète: docs/CONSUMPTION_PREDICTION.md
# Exemples SQL: examples/sensors_sql_consumption.yaml
# Blueprint source: blueprints/smart_battery_charge_tempo.yaml
# Support: https://github.com/foXaCe/enphase-battery/issues
