blueprint:
  name: Gestion Intelligente Charge Batterie Enphase (Tempo + Météo)
  description: >
    Gère automatiquement la charge de la batterie Enphase en fonction :
    - Des heures creuses (optimisation tarifaire)
    - Des jours EDF Tempo (charge à 100% avant jours rouges)
    - De la météo à venir (production solaire prévue)
    - De l'état de charge actuel de la batterie


    **Fonctionnalités :**
    - ⚡ Active la charge depuis le réseau en heures creuses
    - 🔴 Charge forcée à 100% avant les jours rouges Tempo
    - ☀️ Désactive la charge si météo favorable (production solaire suffisante)
    - 🔋 Optimise selon le SOC (State of Charge) actuel

  domain: automation
  source_url: https://github.com/foXaCe/enphase-battery/blob/main/blueprints/smart_battery_charge_tempo.yaml

  input:
    battery_soc_sensor:
      name: Capteur SOC Batterie
      description: Capteur indiquant le pourcentage de charge de la batterie (0-100%)
      selector:
        entity:
          filter:
            - domain: sensor
              device_class: battery

    battery_capacity:
      name: Capacité Batterie
      description: Capacité totale de la batterie en kWh (ex. 5 pour IQ 5P)
      default: 5.0
      selector:
        number:
          min: 1.0
          max: 50.0
          step: 0.1
          unit_of_measurement: "kWh"

    battery_charge_power:
      name: Puissance de Charge
      description: Puissance de charge depuis le réseau en kW (ex. 3.84 pour IQ 5P)
      default: 3.84
      selector:
        number:
          min: 1.0
          max: 10.0
          step: 0.1
          unit_of_measurement: "kW"

    charge_from_grid_switch:
      name: Switch Charge depuis Réseau
      description: Switch pour activer/désactiver la charge depuis le réseau (ex. switch.enphase_battery_charge_from_grid)
      selector:
        entity:
          filter:
            - domain: switch

    tempo_today_sensor:
      name: Capteur Tempo Aujourd'hui
      description: Capteur indiquant la couleur Tempo du jour (Bleu/Blanc/Rouge)
      selector:
        entity:
          filter:
            - domain: sensor

    tempo_tomorrow_sensor:
      name: Capteur Tempo Demain
      description: Capteur indiquant la couleur Tempo du lendemain (Bleu/Blanc/Rouge)
      selector:
        entity:
          filter:
            - domain: sensor

    heures_creuses_start:
      name: Début Heures Creuses
      description: Heure de début des heures creuses
      default: "22:30:00"
      selector:
        time:

    heures_creuses_end:
      name: Fin Heures Creuses
      description: Heure de fin des heures creuses
      default: "06:30:00"
      selector:
        time:

    weather_entity:
      name: Entité Météo
      description: Entité météo pour prévisions (ex. weather.home)
      selector:
        entity:
          filter:
            - domain: weather

    solar_forecast_sensor:
      name: Capteur Prévision Production Solaire
      description: Capteur estimant la production solaire du jour (kWh) - ex. sensor.energy_production_today
      default: ""
      selector:
        entity:
          filter:
            - domain: sensor

    solar_forecast_threshold_low:
      name: Seuil Production Faible
      description: En-dessous de cette production prévue (kWh), charge à 100% (0 = désactivé)
      default: 5.0
      selector:
        number:
          min: 0
          max: 50
          step: 0.5
          unit_of_measurement: "kWh"

    solar_forecast_threshold_medium:
      name: Seuil Production Moyenne
      description: Production moyenne (kWh) - ajuste le SOC cible proportionnellement
      default: 15.0
      selector:
        number:
          min: 0
          max: 100
          step: 0.5
          unit_of_measurement: "kWh"

    min_soc_charge:
      name: SOC Minimum pour Charge
      description: En-dessous de ce seuil, active la charge en heures creuses (%)
      default: 30
      selector:
        number:
          min: 10
          max: 90
          step: 5
          unit_of_measurement: "%"

    target_soc_end_offpeak:
      name: SOC Minimum Fin Heures Creuses
      description: SOC minimum souhaité à la fin des heures creuses (%)
      default: 80
      selector:
        number:
          min: 50
          max: 100
          step: 5
          unit_of_measurement: "%"

    target_soc_tempo_rouge:
      name: SOC Cible Tempo Rouge
      description: Niveau de charge cible avant un jour rouge Tempo (%)
      default: 100
      selector:
        number:
          min: 80
          max: 100
          step: 5
          unit_of_measurement: "%"

    sunny_forecast_threshold:
      name: Seuil Météo Ensoleillée
      description: Nombre de jours ensoleillés prévus pour désactiver charge (0 = désactivé)
      default: 1
      selector:
        number:
          min: 0
          max: 3
          step: 1

variables:
  battery_soc: !input battery_soc_sensor
  battery_capacity_kwh: !input battery_capacity
  charge_power_kw: !input battery_charge_power
  tempo_today: !input tempo_today_sensor
  tempo_tomorrow: !input tempo_tomorrow_sensor
  weather: !input weather_entity
  solar_forecast: !input solar_forecast_sensor
  solar_low: !input solar_forecast_threshold_low
  solar_medium: !input solar_forecast_threshold_medium
  min_soc: !input min_soc_charge
  target_end_offpeak_base: !input target_soc_end_offpeak
  target_rouge: !input target_soc_tempo_rouge
  sunny_threshold: !input sunny_forecast_threshold
  # Calcul du SOC cible dynamique basé sur la prévision solaire
  target_end_offpeak: >
    {% if solar_forecast == "" or solar_low == 0 %}
      {{ target_end_offpeak_base }}
    {% else %}
      {% set forecast_kwh = states(solar_forecast) | float(0) %}
      {% if forecast_kwh <= solar_low %}
        100
      {% elif forecast_kwh >= solar_medium %}
        {{ target_end_offpeak_base }}
      {% else %}
        {# Interpolation linéaire entre low et medium #}
        {% set ratio = (forecast_kwh - solar_low) / (solar_medium - solar_low) %}
        {% set dynamic_target = 100 - (ratio * (100 - target_end_offpeak_base)) %}
        {{ dynamic_target | round(0) }}
      {% endif %}
    {% endif %}
  # Calcul du temps de charge nécessaire en heures
  charge_time_needed: >
    {% set current_soc = states(battery_soc) | float(0) %}
    {% set target = target_end_offpeak | float(80) %}
    {% set soc_to_charge = target - current_soc %}
    {% if soc_to_charge <= 0 %}
      0
    {% else %}
      {% set energy_needed = (soc_to_charge / 100) * battery_capacity_kwh %}
      {{ (energy_needed / charge_power_kw) | round(2) }}
    {% endif %}

trigger:
  # Déclenchement à chaque changement de SOC
  - platform: state
    entity_id: !input battery_soc_sensor

  # Déclenchement au début des heures creuses
  - platform: time
    at: !input heures_creuses_start

  # Déclenchement à la fin des heures creuses
  - platform: time
    at: !input heures_creuses_end

  # Déclenchement quand Tempo aujourd'hui change
  - platform: state
    entity_id: !input tempo_today_sensor

  # Déclenchement quand Tempo demain change
  - platform: state
    entity_id: !input tempo_tomorrow_sensor

  # Déclenchement à 18h pour vérifier Tempo lendemain
  - platform: time
    at: "18:00:00"

  # Déclenchement quand la prévision solaire change
  - platform: state
    entity_id: !input solar_forecast_sensor

condition: []

action:
  - choose:
      # CAS 0: BLOQUAGE - Jour rouge Tempo AUJOURD'HUI → JAMAIS de charge depuis réseau
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: !input tempo_today_sensor
                state: "RED"
              - condition: state
                entity_id: !input tempo_today_sensor
                state: "Rouge"
              - condition: state
                entity_id: !input tempo_today_sensor
                state: "red"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input charge_from_grid_switch
          - service: notify.notify
            data:
              title: "🔴 Batterie - Jour Rouge Tempo"
              message: "Charge désactivée (jour rouge = tarif élevé)"

      # CAS 1: Heures creuses + Tempo ROUGE demain → Charge forcée à 100%
      - conditions:
          - condition: time
            after: !input heures_creuses_start
            before: !input heures_creuses_end
          - condition: or
            conditions:
              - condition: state
                entity_id: !input tempo_tomorrow_sensor
                state: "RED"
              - condition: state
                entity_id: !input tempo_tomorrow_sensor
                state: "Rouge"
              - condition: state
                entity_id: !input tempo_tomorrow_sensor
                state: "red"
          - condition: numeric_state
            entity_id: !input battery_soc_sensor
            below: !input target_soc_tempo_rouge
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input charge_from_grid_switch
          - service: notify.notify
            data:
              title: "🔴 Batterie - Charge Tempo Rouge"
              message: "Charge activée (Tempo Rouge demain) → Cible {{ target_rouge }}%"

      # CAS 2: Heures creuses + calcul intelligent du moment de charge
      - conditions:
          - condition: time
            after: !input heures_creuses_start
            before: !input heures_creuses_end
          - condition: numeric_state
            entity_id: !input battery_soc_sensor
            below: !input target_soc_end_offpeak
          - condition: template
            value_template: >
              {% set forecast = state_attr(weather, 'forecast') %}
              {% if forecast is not none and forecast|length > 0 %}
                {% set sunny_days = forecast[:sunny_threshold]|selectattr('condition', 'in', ['sunny', 'partlycloudy'])|list|length %}
                {{ sunny_days < sunny_threshold }}
              {% else %}
                true
              {% endif %}
          - condition: template
            value_template: >
              {# Toujours charger si SOC bas, sinon calcul intelligent du timing #}
              {% set current_soc = states(battery_soc) | float(0) %}
              {% set target = target_end_offpeak | float(80) %}

              {# Si SOC très bas (< 50%), charger immédiatement #}
              {% if current_soc < 50 %}
                true
              {% else %}
                {# Calcul du temps restant - approximation simple basée sur l'heure #}
                {% set current_hour = now().hour + (now().minute / 60) %}
                {% set end_hour = 6.5 %}  {# 06:30 par défaut #}

                {% if current_hour < end_hour %}
                  {% set hours_remaining = end_hour - current_hour %}
                {% else %}
                  {% set hours_remaining = (24 - current_hour) + end_hour %}
                {% endif %}

                {# Calcul du temps de charge nécessaire #}
                {% set soc_to_charge = target - current_soc %}
                {% set energy_needed = (soc_to_charge / 100) * battery_capacity_kwh %}
                {% set charge_hours_needed = (energy_needed / charge_power_kw) %}

                {# Charger si le temps restant <= temps nécessaire + marge de 0.5h #}
                {{ hours_remaining <= (charge_hours_needed + 0.5) }}
              {% endif %}
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input charge_from_grid_switch
          - service: notify.notify
            data:
              title: "⚡ Batterie - Charge Heures Creuses Optimisée"
              message: >
                Charge démarrée (SOC {{ states(battery_soc) }}%)
                Cible dynamique: {{ target_end_offpeak }}%
                {% if solar_forecast != "" %}
                Production prévue: {{ states(solar_forecast) }} kWh
                {% endif %}
                Temps estimé: {{ charge_time_needed }}h

      # CAS 3: SOC critique (< min_soc) → Charge forcée même hors heures creuses
      - conditions:
          - condition: numeric_state
            entity_id: !input battery_soc_sensor
            below: !input min_soc_charge
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input charge_from_grid_switch
          - service: notify.notify
            data:
              title: "⚠️ Batterie - Charge d'Urgence"
              message: "SOC critique {{ states(battery_soc) }}% - Charge activée"

      # CAS 4: Hors heures creuses OU cible fin HC atteinte → Désactiver charge
      - conditions:
          - condition: or
            conditions:
              - condition: not
                conditions:
                  - condition: time
                    after: !input heures_creuses_start
                    before: !input heures_creuses_end
              - condition: numeric_state
                entity_id: !input battery_soc_sensor
                above: !input target_soc_end_offpeak
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input charge_from_grid_switch

mode: single
max_exceeded: silent
